### ISSUE TITLE
onboarding: go to step 5 impossible

### ISSUE THREAD

**Issue by JacquesBonet** [welovedevs/bug-tracker-public#52]
Impossible to go to step 5 of the onboarding. Nothing happen when I select the next button.

Maybe its because I'hve many experiences.

**Comment by VincentCtr** [comment]
Hello @JacquesBonet ,

Thank you for your issue. I had a look into your data and it seems that you can't go to the step 5 because some data is missing in the step 4 : the location for each of your experiences.

We are working on this issue but we are currently not able to parse the locations of experiences. 

Let met know if you can go to step 5 after you filled locations.

Vincent
